quirk:
  name: "Coordinator Events Relay"
  env: "./.env"
  batch_size: 50  # events
  loop_interval: 120  # seconds

web3:
  infura: "{{ INFURA_API_KEY }}"

bot:
  token: "{{ DISCORD_BOT_TOKEN }}"
  prefix: '!'
  subscribers:
    - name: "QuirkBot Test Server"
      channel_id: "{{ SUBSCRIBER_CHANNEL_ID }}"
      description: "Test discord server description"

events:
  - address: "0xF429C1f2d42765FE2b04CC62ab037564C2C66e5E"
    name: "Coordinator"
    description: "Lynx Domain Coordinator Events"
    chain_id: 137
    abi_file: './abis/coordinator.json'
    events:
      - StartRitual
      - StartAggregationRound
      - EndRitual
      - TranscriptPosted
      - AggregationPosted
      - TimeoutChanged
      - MaxDkgSizeChanged
      - ParticipantPublicKeySet

  - address: "0x8E49989F9D3aD89c8ab0de21FbA2E00C67ca872F"
    description: "Tapir Domain Coordinator Events"
    chain_id: 137
    abi_file: './abis/coordinator.json'
    events:
      - StartRitual
      - StartAggregationRound
      - EndRitual
      - TranscriptPosted
      - AggregationPosted
      - TimeoutChanged
      - MaxDkgSizeChanged
      - ParticipantPublicKeySet
