pique:
  name: "ERC20 Transfer Scanner"
  env: "./.env"

discord:
  token: "{{ DISCORD_BOT_TOKEN }}"
  command_prefix: '!'
  subscribers:
    - name: "PiqueBot Test Server"
      channel_id: "{{ SUBSCRIBER_CHANNEL_ID }}"
      description: "Test discord server description"

contracts:
  infura: "{{ INFURA_API_KEY }}"
  etherscan: "{{ ETHERSCAN_API_KEY }}"
  batch_size: 200  # blocks
  loop_interval: 180  # seconds
  track:
    - name: "DAI"
      address: "0x6B175474E89094C44Da98b954EedeAC495271d0F"
      description: "Mainnet DAI Transferred"
      color: 000000
      chain_id: 1
      status: true
      events:
        - Transfer
