pique:
  name: "DKG Event Scanner"
  env: "./.env"

discord:
  token: "{{ DISCORD_BOT_TOKEN }}"
  command_prefix: '!'
  subscribers:
    - name: "PiqueBot Test Server"
      channel_id: "{{ SUBSCRIBER_CHANNEL_ID }}"
      description: "Test discord server description"

contracts:
  infura: "{{ INFURA_API_KEY }}"
  etherscan: "{{ ETHERSCAN_API_KEY }}"
  batch_size: 200  # blocks
  loop_interval: 180  # seconds
  track:
  - name: "Coordinator"
    address: "0xE9e94499bB0f67b9DBD75506ec1735486DE57770"
    description: "Lynx Domain DKG"
    chain_id: 80002
    abi_file: './abis/CoordinatorLynx.json'
    events:
      - EndRitual
      - StartRitual
  - name: "Coordinator"
    address: "0xE690b6bCC0616Dc5294fF84ff4e00335cA52C388"
    description: "Tapir Domain DKG"
    chain_id: 80002
    abi_file: './abis/CoordinatorTapir.json'
    events:
      - StartRitual
      - EndRitual
