quirk:
  name: "DKG Event Scanner"
  env: "./.env"
  batch_size: 500  # events
  loop_interval: 120  # seconds
  infura: "{{ INFURA_API_KEY }}"
  discord: "{{ DISCORD_BOT_TOKEN }}"
  command_prefix: '!'
  subscribers:
    - name: "QuirkBot Test Server"
      channel_id: "{{ SUBSCRIBER_CHANNEL_ID }}"
      description: "Test discord server description"

contracts:
  - name: "Coordinator"
    address: "0x8E49989F9D3aD89c8ab0de21FbA2E00C67ca872F"
    description: "Lynx Domain DKG"
    chain_id: 80001
    abi_file: './abis/Coordinator.json'
    events:
      - EndRitual
      - StartRitual
  - name: "Coodinator"
    address: "0xF429C1f2d42765FE2b04CC62ab037564C2C66e5E"
    description: "Tapir Domain DKG"
    chain_id: 80001
    abi_file: './abis/Coordinator.json'
    events:
      - StartRitual
      - EndRitual
